FROM node:18.12.1-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN yarn install --frozen-lockfile
RUN yarn global add react-scripts
COPY . .
RUN yarn run build

# production environment
FROM nginx:1.24-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./deployment/nginx/default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
